# Generated by Django 4.2.1 on 2023-05-30 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_coluna', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Coluna')),
                ('conteudo_anonimizado', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=255, null=True, verbose_name='Conteúdo Anonimizado')),
                ('justificativa_para_uso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Coluna')),
            ],
            options={
                'verbose_name': 'LGPD',
                'verbose_name_plural': 'LGPD',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('grau_status', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=255, null=True, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Responsavel',
                'verbose_name_plural': 'Responsaveis',
            },
        ),
        migrations.CreateModel(
            name='TipoDistribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo Distribuidora',
                'verbose_name_plural': 'Tipos Distribuidora',
            },
        ),
        migrations.CreateModel(
            name='TipoEntidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo Entidade',
                'verbose_name_plural': 'Tipos Entidade',
            },
        ),
        migrations.CreateModel(
            name='TipoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo Grupo',
                'verbose_name_plural': 'Tipos Grupo',
            },
        ),
        migrations.CreateModel(
            name='TipoOrigemDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo Origem Dados',
                'verbose_name_plural': 'Tipos Origem Dados',
            },
        ),
        migrations.CreateModel(
            name='Tabelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tabela', models.CharField(max_length=255, verbose_name='Nome Tabela')),
                ('origem_dados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas', to='core.tipoorigemdados', verbose_name='Tipo Origem Dados')),
            ],
            options={
                'verbose_name': 'Tabela',
                'verbose_name_plural': 'Tabelas',
            },
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('caminho', models.CharField(max_length=255, verbose_name='Caminho')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('responsavel_uso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsavel Uso')),
                ('publico_alvo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Público-alvo')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_repo_responsavel', to='core.responsavel', verbose_name='Responsavel')),
                ('tipo_distribuidora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo', to='core.tipodistribuidora', verbose_name='Tipo Distribuidora')),
                ('tipo_entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo', to='core.tipoentidade', verbose_name='Tipo Entidade')),
            ],
            options={
                'verbose_name': 'Repo',
                'verbose_name_plural': 'Repos',
            },
        ),
        migrations.CreateModel(
            name='RegistroDeVersoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.IntegerField(verbose_name='Versão')),
                ('ticket', models.CharField(max_length=255, verbose_name='Ticket')),
                ('comentario', models.CharField(max_length=255, verbose_name='Comentário')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_de_versoes', to='core.responsavel', verbose_name='Responsavel')),
            ],
            options={
                'verbose_name': 'Registro de Versão',
                'verbose_name_plural': 'Registro de Versões',
            },
        ),
    ]
