# Generated by Django 4.2.1 on 2023-05-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='data_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Update'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='usuario_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Usuário Update'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='valido',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('N', 'N')], max_length=255, null=True, verbose_name='Válido'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='grau_status',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=255, null=True, verbose_name='Nome'),
        ),
    ]
