# Generated by Django 4.2.1 on 2023-05-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_responsavel_data_update_responsavel_usuario_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Aba',
                'verbose_name_plural': 'Abas',
            },
        ),
        migrations.CreateModel(
            name='Querys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('query', models.CharField(max_length=255, verbose_name='Query')),
                ('tempo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tempo')),
                ('linhas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Linhas')),
                ('colunas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Colunas')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Querys',
            },
        ),
    ]
