# Generated by Django 4.2.1 on 2023-05-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_abas_querys'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='registro_versoes',
            field=models.ManyToManyField(to='core.registrodeversoes', verbose_name='Registro de Versões'),
        ),
    ]
