# Generated by Django 4.2.1 on 2023-05-31 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_repo_registro_versoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='registro_versoes',
        ),
        migrations.AddField(
            model_name='abas',
            name='id_repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.repo', verbose_name='Repo'),
        ),
        migrations.AddField(
            model_name='lgpd',
            name='id_repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.repo', verbose_name='Repo'),
        ),
        migrations.AddField(
            model_name='querys',
            name='id_repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.repo', verbose_name='Repo'),
        ),
        migrations.AddField(
            model_name='registrodeversoes',
            name='id_repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.repo', verbose_name='Repo'),
        ),
        migrations.AddField(
            model_name='tabelas',
            name='id_repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.repo', verbose_name='Repo'),
        ),
    ]
